services:
  tts:
    build: .
    container_name: piper-tts
    environment:
      - TTS_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - /outputs:/outputs  # Para guardar los audios generados en local
    restart: unless-stopped
